
import React, { useState, useEffect } from 'react';
import { storageService } from '../services/storageService';
import { geminiService } from '../services/geminiService';
import { KnowledgeEntry, User } from '../types';

interface SearchInterfaceProps {
  user: User | null;
  onNotFound: (query: string) => void;
  selectedEntry?: KnowledgeEntry | null;
}

export const SearchInterface: React.FC<SearchInterfaceProps> = ({ user, onNotFound, selectedEntry }) => {
  const [query, setQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [result, setResult] = useState<KnowledgeEntry | null>(null);
  const [sourceLabel, setSourceLabel] = useState<string>('');
  const [isBookmarked, setIsBookmarked] = useState(false);

  useEffect(() => {
    if (selectedEntry) {
      setResult(selectedEntry);
      setQuery(selectedEntry.title);
      setSourceLabel('Loaded from your bookmarks');
      if (user) {
        setIsBookmarked(storageService.isBookmarked(user.id, selectedEntry.id));
      }
    }
  }, [selectedEntry, user]);

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsSearching(true);
    setResult(null);

    // Record History
    if (user) {
      storageService.addHistory(user.id, query.trim());
    }

    // 1. Check "Database"
    const localEntry = storageService.search(query);
    
    if (localEntry) {
      setResult(localEntry);
      setSourceLabel('Retrieved from local database');
      if (user) setIsBookmarked(storageService.isBookmarked(user.id, localEntry.id));
      setIsSearching(false);
    } else {
      // 2. AI Fallback
      setSourceLabel('Searching AI knowledge base...');
      const aiContent = await geminiService.generateDefinition(query);
      
      if (aiContent) {
        // 3. Auto-Save
        const newEntry = storageService.save(query, aiContent, 'ai');
        setResult(newEntry);
        setSourceLabel('Generated by Gemini AI (Auto-saved)');
        if (user) setIsBookmarked(storageService.isBookmarked(user.id, newEntry.id));
        setIsSearching(false);
      } else {
        // 4. Fail
        setIsSearching(false);
        onNotFound(query);
      }
    }
  };

  const handleBookmarkToggle = () => {
    if (!user || !result) return;
    storageService.toggleBookmark(user.id, result.id);
    setIsBookmarked(!isBookmarked);
  };

  return (
    <div className="space-y-8">
      <div className="text-center space-y-2 mb-10">
        <h2 className="text-4xl font-extrabold text-slate-900 tracking-tight">Smart Search Engine</h2>
        <p className="text-slate-500 text-lg max-w-xl mx-auto">Instant knowledge powered by AI and persistent local indexing.</p>
      </div>

      <form onSubmit={handleSearch} className="relative max-w-2xl mx-auto group">
        <div className="absolute inset-0 bg-blue-400/20 blur-2xl rounded-3xl group-focus-within:bg-blue-500/30 transition-all"></div>
        <div className="relative">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search anything..."
            className="w-full pl-14 pr-32 py-5 rounded-3xl border-2 border-white focus:border-blue-500 outline-none transition-all text-xl shadow-2xl bg-white/90 backdrop-blur-xl"
            disabled={isSearching}
          />
          <i className="fas fa-search absolute left-6 top-1/2 -translate-y-1/2 text-slate-400 text-xl group-focus-within:text-blue-500"></i>
          <button
            type="submit"
            disabled={isSearching || !query.trim()}
            className="absolute right-3 top-1/2 -translate-y-1/2 bg-blue-600 hover:bg-blue-700 text-white px-8 py-3 rounded-2xl font-bold shadow-lg disabled:opacity-50 transition-all flex items-center gap-2"
          >
            {isSearching ? <i className="fas fa-spinner fa-spin"></i> : 'Discover'}
          </button>
        </div>
      </form>

      {result && (
        <div className="max-w-2xl mx-auto bg-white border border-slate-200 rounded-3xl shadow-2xl overflow-hidden animate-fade-in relative">
          <div className="p-6 border-b border-slate-100 flex items-center justify-between bg-slate-50/50">
            <div className="flex items-center gap-4">
               <h3 className="text-2xl font-bold text-slate-900 capitalize">{result.title}</h3>
               <span className={`px-3 py-1 rounded-lg text-[10px] font-black uppercase tracking-tighter ${
                result.source === 'database' ? 'bg-emerald-100 text-emerald-700' : 
                result.source === 'ai' ? 'bg-indigo-100 text-indigo-700' : 'bg-amber-100 text-amber-700'
              }`}>
                {result.source}
              </span>
            </div>
            {user && (
              <button 
                onClick={handleBookmarkToggle}
                className={`w-12 h-12 rounded-2xl flex items-center justify-center transition-all ${
                  isBookmarked 
                  ? 'bg-yellow-50 text-yellow-500 shadow-inner' 
                  : 'bg-slate-100 text-slate-400 hover:bg-yellow-50 hover:text-yellow-500'
                }`}
                title={isBookmarked ? "Remove Bookmark" : "Save to Bookmarks"}
              >
                <i className={`${isBookmarked ? 'fas' : 'far'} fa-star text-lg`}></i>
              </button>
            )}
          </div>
          <div className="p-10">
            <p className="text-slate-700 leading-relaxed text-xl whitespace-pre-wrap font-medium">
              {result.content}
            </p>
          </div>
          <div className="px-10 py-5 bg-slate-50 text-slate-400 text-xs flex items-center justify-between italic border-t border-slate-100">
            <div className="flex items-center gap-2">
              <i className="fas fa-bolt text-blue-500"></i>
              {sourceLabel}
            </div>
            <div>
              {new Date(result.createdAt).toLocaleDateString()}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
